package com.unicosolution.adapter.snowflakev2.wizard;

import com.informatica.tools.adapters.ui.appsdk.wizard.NewDefaultAppDataObjectWizard;

public class SnowflakeV2DataObjectWizard extends NewDefaultAppDataObjectWizard  {
    	/* 
    	 * Get adapter id  
    	 *************************************
    	 * AUTOGENERATED CODE : DO NOT CHANGE
    	 */
    	@Override
    	protected String getAdapterId() {
    		return "com.unicosolution.adapter.snowflakev2";
    	}

}